### ISSUE TITLE
Наследование

### ISSUE THREAD

**Issue by ogonkov** [bem-site/bem-forum-content-ru#137]
Как правильно реализовать наследование с BEM?

Предположим, у меня есть блок list

``` css
.list {
  font-size: 14px
}
```

и есть блок teaser, где этот list используется с размером шрифта 18px.

Чисто по логике, я бы сделал наверное как-то так:

``` css
.teaser__list {
  font-size: 18px
}
```

Но мои коллеги категорически не приемлют такого решения и утверждают, что мне нужно сделать модификатор от list, увеличивающий размер шрифта:

``` css
.list__text-size_18 {
  font-size: 18px
}
```

Так как правильно?
