### ISSUE TITLE
Наследование с миксином

### ISSUE THREAD

**Issue by ogonkov** [bem-site/bem-forum-content-ru#140]
Ещё возник вопрос, что делать в следующей ситуации. Есть например блок `tile`

``` css
.tile {
  text-align: center;
}
```

и есть миксин `getting-started`

``` css
.getting-started {
  text-align: left;
}
```

Так исторически сложилось, что миксин подключается раньше основных стилей, и выравнивание текста, соответственно, не то, которое мы бы хотели.

Сейчас мы делаем хак для `getting-started`:

``` css
.getting-started.tile {
  text-align: left;
}
```

Но это слегка попахивает. Как разрулить эту ситуацию покрасивее?
