### ISSUE TITLE
CSSComb + BEM

### ISSUE THREAD

**Issue by Kundin** [bem-site/bem-forum-content-ru#1454]
Привет!
Кто может подсказать как настроить ```csscomb``` для стилей написанных по БЭМу:

```css
block(chat) {
    position: relative;

    elem(head) {
        display: flex;
    }
}
```
Кажется, находил плагин ```postcss-csscomb```, но он мне не сильно помог.
В идеале какое-то решение для ST3, чтобы ```Ctrl+Shift+C``` и все работало.

Или нужно просто правильно настроить ```CSSComb```?

**Comment by godfreyd** [comment]
Привет. @tadatuta , посмотри, пожалуйста.

**Comment by tadatuta** [comment]
Поможет stylelint + https://www.npmjs.com/package/stylelint-order

**Comment by Kundin** [comment]
@tadatuta, Спасибо. Работает из терминала, но немного не так сортируются свойства.
```css
block(test) {
    bottom: 10px;
    display: flex;
    justify-content: center;

    position: absolute;
    width: 100%;
    z-index: 60;
}
```
Я так понимаю порядок сортировки свойств настраивается в ```.stylelintrc```?
Возможно есть  где-то готовый конфиг? 
Меня полностью устраила бы сортировка свойств как в ```bem-components```
