### ISSUE TITLE
библиотека компонентов css

### ISSUE THREAD

**Issue by pj-media** [bem-site/bem-forum-content-ru#1458]
можно ли каким то образом получить доступ к скомпилированному css отдельных компонентов библиотеки для использования в своем проекте?

**Comment by Kundin** [comment]
Вполне можно взять css из `bem-components`, останется лишь правильно писать классы и делать правильную структуру HTML.
Например, вот CSS блока `spin`  с темой `islands`
```css
.spin_theme_islands {
    position: absolute;

    display: inline-block;
    visibility: hidden;

    box-sizing: border-box;
    border: 2px solid transparent;
    border-radius: 50%;
}

.spin_theme_islands:after {
    content: '\00A0';
}

.spin_theme_islands.spin_visible {
    position: relative;
    visibility: visible;
    -webkit-animation: spin_theme_islands 1s infinite linear;
            animation: spin_theme_islands 1s infinite linear;
    background: 0 0 no-repeat url(spin_theme_islands.gif);
    /* `1deg` is needed to prevent FF bug after minification (`0deg` => `0`) */
    background: linear-gradient(1deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0));
    -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
    /* Accelerate animation */
}

.spin_theme_islands.spin_size_xs {
    line-height: 16px;
    width: 16px;
    height: 16px;
    background-position: -2px -2px;
}

.spin_theme_islands.spin_size_s {
    line-height: 24px;
    width: 24px;
    height: 24px;
    background-position: -2px -19px;
}

.spin_theme_islands.spin_size_m {
    line-height: 28px;
    width: 28px;
    height: 28px;
    background-position: -2px -44px;
}

.spin_theme_islands.spin_size_l {
    line-height: 32px;
    width: 32px;
    height: 32px;
    background-position: -2px -73px;
}

.spin_theme_islands.spin_size_xl {
    line-height: 38px;
    width: 38px;
    height: 38px;
    background-position: -2px -106px;
}

@-webkit-keyframes spin_theme_islands {
    from {
        border-top-color: #fc0;
        border-left-color: #fc0;
        -webkit-transform: rotate(0);
                transform: rotate(0);
    }
    to {
        border-top-color: #fc0;
        border-left-color: #fc0;
        -webkit-transform: rotate(360deg);
                transform: rotate(360deg);
    }
}

@keyframes spin_theme_islands {
    from {
        border-top-color: #fc0;
        border-left-color: #fc0;
        -webkit-transform: rotate(0);
                transform: rotate(0);
    }
    to {
        border-top-color: #fc0;
        border-left-color: #fc0;
        -webkit-transform: rotate(360deg);
                transform: rotate(360deg);
    }
}
```
Тогда чтобы разместить этот блок вы должны написать такой HTML
```html
<span class="spin spin_theme_islands spin_size_m spin_visible"></span>
```

Но это самый простой блок и, если честно, немного изврат =)

CSS каждого блока можно взять в [bem-components/design](https://github.com/bem/bem-components/tree/v6.0.0/design)
