### ISSUE TITLE
Специфичность и modernizr

### ISSUE THREAD

**Issue by exeto** [bem-site/bem-forum-content-ru#663]
Как лучше утяжелить селектор при использовании modernizr? Единственное что приходит на ум, использование `!important`. Но это считается плохой практикой.

``` css
.block {
  color: red;
}

.no-feature .block {
  color: blue;
}

.block--mod {
  color: green !important;
}
```

**Comment by tadatuta** [comment]
Можно, например, ввести соглашение, что для увеличения веса используется класс самого первого родителя:

```css
.block {
  color: red;
}

.no-feature .block {
  color: blue;
}

.page .block--mod {
  color: green;
}
```
